### ISSUE TITLE
Auto-start (or kiosk mode)

### ISSUE THREAD

**Issue by ny4i** [n1kdo/n1mm_view#1]
Hi. This is exactly what I was think about doing. Always glad to find an idea already coded. I am curious if you see any issues if I make this more like a Kiosk. My main concern is if the Pi lost power for some reason, I would want it to just come back up upon restart so essentially boot to running the display with no keyboard interaction.

Unless there is some issue with that, I will look at that after I get the basics running.

Thanks, Tom Ny4I

**Comment by n1kdo** [comment]
Hi,  I never built any init scripts for this.  It should be trivial, start the collector process, start the dashboard.

I actually don't know how the raspbian init works.  I would happily look at a pull request that had the scripts.

73

**Comment by n1kdo** [comment]
I have added systemd control files for the collector and dashboard, and updated the install doc to describe how they work.  

"They work on my system."  That is as much testing as they have at this time.

The collector and dashboard will start at boot time using this configuration.
