### ISSUE TITLE
Pi and WIndows questions

### ISSUE THREAD

**Issue by ag6ay** [n1kdo/n1mm_view#12]
Hi
I have some questions and observations.  I'm looking forward to comments
Cheers
Rick AG6AY

**Installing on Pi using Stretch**
1. I found line 51 in graphics.py needed 'x11' in the list before init_display() would work
   (the full list of possible values is at https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlenvvars.html) but debian-based Pi only needed 'x11' added)
2. I found packages python-pygame and numpy pre-installed installed with Stretch and I did not need to add them manually.
3. I did not need to build basemap ... this seemed to work ...

After installing Stretch ...
sudo aptitude update
sudo aptitude upgrade
sudo aptitude install libgeos-3.5.1
sudo aptitude install libgeos-dev
sudo aptitude install python-matplotlib
sudo aptitude install python-mpltoolkits.basemap
git clone <repo location>

I say seemed to work because running the ./collector.py and ./dashboard.py brings up the logo and marque moving line at the bottom of the screen but i have not yet gotten the various dashboards to visually cycle on the screen. 

Do I need data in the database first?  
Can you provide more instructions on using replayer.py?

**Installing on Windows**
1. I am stuck on Step 14 and 15 of INSTALL_WINDOWS.md.  "call ..\Scripts\activate.bat" finds nothing to execute.

**Comment by n1kdo** [comment]
Hi,

You probably need to add x11 if you are running x-window system.  I never did that.  Please make a pull request so that can get added.

Until there is data, not much should show, except for the map.

I don't know about the windows installation.  You might want to ask VE1GPY, he gave me that.

to use replayer, change the name of the N1MM_LOG_FILE in config.py to point at a log file you want to process into the system.  This simulates the UDP messages from N1MM and sends them to the collector.  if you have a old log file from field day, you can use this to test.

**Comment by ag6ay** [comment]
Thanks for the info

What I meant by ....

"I found line 51 in graphics.py needed 'x11' in the list before init_display() would work
(the full list of possible values is at https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlenvvars.html) but debian-based Pi only needed 'x11' added)"

... is that, with the current Stretch Raspbian version, the dashboard.py log was showing 'No suitable video driver found!' before terminating until I made the following change in graphics.py ...

From:     drivers = ['fbcon', 'directfb', 'ggi', 'svgalib', 'directx', 'windib']
to:     drivers = ['x11', 'fbcon', 'directfb', 'ggi', 'svgalib', 'directx', 'windib']

... after which the program does not terminate and the logo with scrolling marque line is presented.  I do not get a map, however.

I did not actually have to install x-windows ... it was already part of Stretch and was the driver os.putenv('SDL_VIDEODRIVER', driver) needed for my OS.

So I should have seen a basic map?  Hmm.  Perhaps sudo aptitude install python-mpltoolkits.basemap did not work for me after all.  I will look over weekend.

**Comment by ag6ay** [comment]
I would like to request write access so that I can create an x11 branch using ...
git push origin x11

**Comment by n1kdo** [comment]
Fork then push to your fork and make a pull request.  Thanks!

**Comment by n1kdo** [comment]
the main branch now has 

drivers = ['x11', 'fbcon', 'directfb', 'ggi', 'svgalib', 'directx', 'windib']

so I am closing this issue.
