### ISSUE TITLE
Sorry I'm new at this!

### ISSUE THREAD

**Issue by devildog1977** [n1kdo/n1mm_view#15]
Following your directions, and trying to start the ./dashboard.py I'm getting an error that says No Module named basemap. The whole error reads this 

Traceback (most recent call last):
File "./dashboard.py", line 19 in <module>
import graphics 
File "/home/pi/nimm_view/graphics/py". line 17 in <module>
from mpl_toolkits.basemap import Basemap
Import Error: No module named basemap

I also had to get the basemap from this location instead of the one mentioned in the directions. 
https://sourceforge.mirrorservice.org/m/ma/matplotlib/matplotlib-toolkits/basemap-1.0.7/

I was getting a 404 error with the link in your directions, not sure if that was the problem or not.  I'm sorry for being a newb and asking this question. 

Thanks in advance!

**Comment by n1kdo** [comment]
What platform?  Windows, Linux-x86 or Raspberry Pi?  I have not tried to install fresh for a while.

**Comment by devildog1977** [comment]
Hello Sir, I was trying to install it on the last eat version of Raspberry Pi.

Thanks in adavance

**Comment by n1kdo** [comment]
Hi,  I have not had much time to work on this code for a while, and that trend is likely to continue.

It sounds like that there is an issue installing Basemap.  This looks to be the official version: https://sourceforge.net/projects/matplotlib/files/matplotlib-toolkits/ -- the tarball is at https://sourceforge.net/projects/matplotlib/files/matplotlib-toolkits/basemap-1.0.7/basemap-1.0.7.tar.gz/download

Please let me know if/how you get it working.  If you are just fooling around with it, then it is a whole lot easier to install the "wheels" on Windows, getting all the pieces built for Raspberry Pi is painful and time consuming.

**Comment by devildog1977** [comment]
Hey Jeff, understood I’ll try both approaches. Would you happen to know what version of Raspberry PI you had the development on? I just plan on using the view at field day this year, broadcast it on a tv for visitors to see our contacts. Anyway thanks for getting back to me!

Scott 
Ko4w

**Comment by k0pci** [comment]
Scott, 
Were you able to resolve?  
With a current Raspbian image, it is not necessary to manually download and compile matplotlib or basemap.
Just do:
$ sudo apt-get install -y python-matplotlib`
$ sudo apt-get install -y python-mpltoolkits.basemap
Each of these will take several minutes.  Don't try to do both at once.

**Comment by devildog1977** [comment]
Hey there

I haven’t tried that but definitely will try it, want to get this up and going before field day. 

Thanks for the follow up

Scott

**Comment by devildog1977** [comment]
Hi again

Ok I'm definitely getting closer,

Now it says n4n Field Day 2016

Scrolling at the bottom Chart engine failed, N4N Field Day 23:17:24 N4F
Field Day is over.

Any thoughts?

Scott

Scott

**Comment by n1kdo** [comment]
edit config.py.  change the date there.  Good luck on field day.

**Comment by devildog1977** [comment]
Hey there, I did that and it did change the date. Now the date is showing correctly, saying field day starts in 25 days, but now the "Chart Engine" is red and says failed. My collector.py is giving data e.g. "received score message" etc. so I think that's correct. Thoughts?

**Comment by n1kdo** [comment]
Hi, when the display shows that "Chart Engine Failed" there should be an error with a traceback in the console, where the program sends its output. Can you find the error message?

**Comment by ke0pci** [comment]
For testing, set the event to start yesterday.

If the Collector is showing that it is reading data, you should be golden.
Setting the event from yesterday through june 23 will make one of the
graphs stretched too far to see detail, but you will see in all other
screens that it is working.

I will work on a new installer and updated usage instructions.

**Comment by n1kdo** [comment]
basemap is kaput, gone.  I replaced it with Cartopy.  This has made the installation process considerably easier.  Hopefully this will correct your issue.

Good luck with Field Day 2020!

I'm closing this issue, since the problem described has been superseded by events.
