### ISSUE TITLE
Basemap is impossible to install

### ISSUE THREAD

**Issue by n1kdo** [n1kdo/n1mm_view#16]
I was going to update N1MM_View to support Python 3 and the latest matplotlib, and I struck out trying to install basemap, it is a giant pain in the ass on Windows, and probably worse on Raspbian.  

I think I want to re-factor the display logic to use javascript libraries d3s for the graphs and leaflet for the mapping.  This will result in the displays needing a modern web browser to run, but will also allow stations on the network to display the graphics as well as the main monitor connected to the Pi.

**Comment by k0pci** [comment]
On current Raspbian, numpy is already set up, and mature packages are available:
python-matplotlib
python-mpltoolkits.basemap

I have installed matplotlib and basemap manually on Pi Zero, and would never wish that horror on anyone.  I hav no input for getting it done on Windows; I don't touch that stuff.

**Comment by n1kdo** [comment]
I am working to convert the map display to use Cartopy. I have a prototype working.  It seems much faster than Basemap.

**Comment by n1kdo** [comment]
I have removed Basemap and replaced it with Cartopy, so this issue is now moot.
