### ISSUE TITLE
UnboundLocalError: local variable 'row' referenced before assignment

### ISSUE THREAD

**Issue by njohnsn** [n1kdo/n1mm_view#19]
I'm getting the following error when dashboard tries to start the chart engine:
(Trying to get running on a RPi 3).

`
Traceback (most recent call last):
  File "./dashboard.py", line 282, in update_charts
    last_qso_timestamp = load_data(size, q, base_map, last_qso_timestamp)
  File "./dashboard.py", line 71, in load_data
    last_qso_time, message = dataaccess.get_last_qso(cursor)
  File "/home/pi/n1mm_view/dataaccess.py", line 110, in get_last_qso
    row[1], row[2], row[3], constants.Bands.BANDS_TITLE[row[5]], row[4],
UnboundLocalError: local variable 'row' referenced before assignment
`

**Comment by njohnsn** [comment]
Looks like you have to have an entry in the collector's database before running the dashboard...

**Comment by n1kdo** [comment]
I believe I fixed this in commit f7e1d85.  Please re-open if this is still a problem for you.  73.
