### ISSUE TITLE
Question about headless.py

### ISSUE THREAD

**Issue by ny4i** [n1kdo/n1mm_view#20]
My use case is I have a single PI that displays the screens on a monitor (or projector) and sends the QSOs to the Internet. When I originally added the coded to create PNG files and upload them, I had it combined. When the code went through its modularization, these functions were separated into dashboard.py and headless.py.

In my use case, would I run two instances (on different Pis)?

I am curious if there is a particular reason the option to have these functions combines was removed from the code?

Thanks, Tom NY4I

**Comment by n1kdo** [comment]
This could probably be further refactored such that the images are all _only_ created as png, and the pygame dashboard just displayed the pngs.

**Comment by n1kdo** [comment]
can I close this issue?
