### ISSUE TITLE
What is needed for the new PE section come April 2020

### ISSUE THREAD

**Issue by ny4i** [n1kdo/n1mm_view#26]
Prince Edward Island becomes its own section in April 2020. Other than adding it to the constants file, how would the images be created to make the section from MAR?

**Comment by n1kdo** [comment]
The shape files for MAR will need to be edited, and a new shape file for PEI (is that the name?) created.  It's been so long since I worked on shape files, I don't remember how to do that.  I'll look into it.

**Comment by ny4i** [comment]
From this article, http://www.arrl.org/news/radio-amateurs-of-canada-announces-a-new-section, it looks like it will be PE.

The number of Sections needed for a clean sweep in the ARRL November Sweepstakes (SS) will rise to 84 in 2020, with the addition of a new Prince Edward Island (PE) Section. Radio Amateurs of Canada (RAC <https://www.rac.ca/>) announced this week that the new Section will become effective on April 1.


Thanks,

Tom NY4I

Principal Solutions Architect
Better Software Solutions, Inc.
727-437-2771

**Comment by n1kdo** [comment]
I added the section to CONTEST_SECTIONS map, and I edited the MAR and created PE shapefiles.  Preliminary testing looks good.  More testing would be useful.  I edited the shapefiles with QGIS.

I believe this should be sufficient to close this issue.
