### ISSUE TITLE
time removed from action chart of headless?

### ISSUE THREAD

**Issue by ny4i** [n1kdo/n1mm_view#28]
I noticed the timestamp was removed from the sections chart. It is updated anyway because of the gray line so I was curious if that was just an oversight. I added awhile ago if I recall as it told me the updates on the website were happening as during the day the gray line does not change.

Any reason I cannot add it back?

Tom

**Comment by n1kdo** [comment]
I expect that was an oversight -- or just plain miss -- on my part, when I refactored the map display to use Cartopy.  There may be more issues, I have not had a lot of time to test that (including whether the gray line moves.)  So... please... by all means... have at it.

73

Jeff
