### ISSUE TITLE
All states?

### ISSUE THREAD

**Issue by ny4i** [n1kdo/n1mm_view#3]
I'm new to the shape files. I wonder if you have any hints on where to look for a state shape for contests that use states? I did a bit of research on country maps but that might be too much. I was thinking states would be useful for state contests like NAQP and QSO Parties.

It would also be useful for events like a local science festival where we can just log state and have it highlight the whole state for when they ask, "How far away have you talked to".

What I am unsure of is if you are gathering counties together to draw the lines in multi-section states so I can make equivalent files of just CA, WA, TX, FL, NY, NJ, PA, MA, etc.

Thanks...

**Comment by n1kdo** [comment]
I think that the MatPlotLib maps have the US states in them.  I don't know
if you can shade those like you can with external shape files.

I had a friend who works in the GIS field make me the shapes for the ARRL
Sections.

Jeff

**Comment by ny4i** [comment]
I have a branch that basically groups the state sections and if we want to highlight CA, it loops turns on all the sections in CA. It's kludgy but I would not figure out how to get a shape for CA, for example. Same for the other multi-section states.

**Comment by ny4i** [comment]
I wanted to revisit this one. I have never liked the kludgy way I used the multiple sections to color in a state. Basically, if the contest QTH is a state (ARRL 10 meter for example), when I see CA, I use a list that tells me all the sections that are in CA and I turn them on (or add a QSO to them). I end up with lines that separate the sections. It is more noticeable in Texas and Florida. Maybe that is an acceptable way to do it for the limited number of non section contests to which this would be used. 

If that sounds like something that is tolerable, I can polish up the patch into a pull request for review. If you know of an easier way to get the shape files (one more reason I am reanimating this issue in case in 2024 we have a better way), let me know.
