### ISSUE TITLE
sudo .rpi_install.sh command not found

### ISSUE THREAD

**Issue by N6WT** [n1kdo/n1mm_view#30]
When I get to sudo ./rpi_install.sh I get the error "command not found". If I do a dir I see the file rpi_install.sh.

**Comment by n1kdo** [comment]
Hi,

That file might not be executable.  you can fix that by doing something like 

```chmod +x rpi_install.sh```

That file was kindly contributed by @ke0pci -- perhaps he will chime in on this.

73

Jeff

**Comment by N6WT** [comment]
Jeff
That seems to have done the trick.

Thanks
73
Kent
N6WT

**Comment by ke0pci** [comment]
That's correct.  When you clone the repo, it downloads the shell script, but will not set the "executable" permission automatically (hey, platform security!).  The full procedure appears in INSTALL_RASPI.md, and would be step 4 for the installation.  You would only need to do the installation once.
