### ISSUE TITLE
Got it working but

### ISSUE THREAD

**Issue by N6WT** [n1kdo/n1mm_view#32]
In the instructions to configure N1MM it says "In the "Broadcast Data" tab, check the box in front of the word "content"." There is not selection for "content" I see "Contacts", is this what it is supposed to be?
![broadcast data](https://user-images.githubusercontent.com/86750386/124187735-19919e80-da73-11eb-88f2-2268247bd78d.jpg)

**Comment by n1kdo** [comment]
should say contacts.  Fixed.
