### ISSUE TITLE
qso_rates_chart tightly bound to BANDS_LIST constant

### ISSUE THREAD

**Issue by ny4i** [n1kdo/n1mm_view#4]
The BANDS_LIST constant included bands that might not be used for all contests (6m, 2m and 440). I removed those bands as I did not want them to appear in the chart, but that qso_rates_chart had an error in this code:
```Python
ax.stackplot(dates, qso_counts[1], qso_counts[2], qso_counts[3], qso_counts[4], qso_counts[5], qso_counts[6],
                     qso_counts[7], qso_counts[8], qso_counts[9], labels=labels, colors=colors, linewidth=0.2)
```

If the select statement (which loads the array is shorter than this line expects, the later arrays are not populated. It would be good to check how many bands are defined and join only those array elements.

I add this as a reminder as I am glad to change that to make this more parameter driven. 

Another way might be to have a definition of type like HF/VHF. As this is Field Day, I can see where the users might want to include VHF and UHF is a free VHF station is being used, but others might like this just for HF—which also makes it easier to extend for other contests like Sweepstakes.

**Comment by n1kdo** [comment]
the matplotlib stackplot might support a call with a 2-d array, but for one reason or another, you can see this is based at index 1.

http://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.stackplot.html

**Comment by ny4i** [comment]
I fixed this—just have to get it into a PULL request. I will do that after FD as we need a quiet point before the contest. The change is in my fork if anyone wants it before FD so you can only display 80m through 10m.

**Comment by n1kdo** [comment]
is this change merged?  I do not recollect.

**Comment by ny4i** [comment]
No it was not. I checked my branch but do not see it so I may have done it on another system but not checked it in. I will have to look around. Ironically, I used 2m this time so this would have been moot. I think you can close it.

**Comment by n1kdo** [comment]
Thanks Tom.  only 10 months until Field Day!
