### ISSUE TITLE
Add support for NS and NB sections.

### ISSUE THREAD

**Issue by ny4i** [n1kdo/n1mm_view#42]
As of January 1, 2023, NB and NS are now valid VE sections. In deference to the shortness of time before Winter Field day,  if NB or NS is received, perhaps MAR could be counted. This is the latest list of the ARRL sections: https://contests.arrl.org/contestmultipliers.php?a=wve

**Comment by n1kdo** [comment]
commit 65d620f removes the MAR shape and adds NB and NS.  

It might work.  I have not tested it.  The regions are properly indicated on the map.

Manipulating the shape files is difficult for me. QGIS and I do not get along.

Please let me know if you have time to try it.

**Comment by ny4i** [comment]
This seems to work fine. Thanks for getting it so fast.

**Comment by n1kdo** [comment]
YW.  Winter field day is soon!  Good luck.
