### ISSUE TITLE
Hints to handle install in a Python environment

### ISSUE THREAD

**Issue by ny4i** [n1kdo/n1mm_view#58]
Given when I ran pip to install numpy, I received this message:

```
pi@bench5:~/n1mm_view$ pip install numpy
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    For more information visit http://rptl.io/venv

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
```

Is there a recommended best practice to handle this (and something we may want to put in the install document)? Last time I did this on Bookwork, I believe I setup Python to not use environments onthe whole system. But I am not sure if that is the recommended step for everyone.

**Comment by ny4i** [comment]
Nevermind. I see the issue. The INSTALL has both these statements: pip install numpy sudo apt install python3-numpy

It needs to use the second one.

Any reason we do not just put the python-numpy install in the rpi_install.sh?

**Comment by n1kdo** [comment]
pull requests accepted with eternal gratitude! 

I do need to get a RPi ready for field day.

**Comment by ny4i** [comment]
I was reminding myself of it and more to check to see if there was a technical reason to do numpy outside of the script. I’m never shy with the pull requests once I have a direction so I’ll proceed that way. :)I was getting things ready too. RegardsTom Principal Solutions ArchitectBetter Software Solutions, Inc.813-205-6388 (mobile/text)On Jun 6, 2024, at 7:34 PM, Jeff Otterson ***@***.***> wrote:﻿
pull requests accepted with eternal gratitude!
I do need to get a RPi ready for field day.

**Comment by n1kdo** [comment]
please go ahead and put a PR on that file.  Thanks.  Jeff
