### ISSUE TITLE
Using the SavetoPNG files option

### ISSUE THREAD

**Issue by ny4i** [n1kdo/n1mm_view#6]
To use this code, one has to define a var called HTML_DIR on the config file. Mine looks like this:
HTML_DIR = '/home/toms/n1mm_view/html'

but I run under my user. This could also be /home/pi/n1mm_view/html or even /var/www/html to keep it simple. As long as the user in question has write access to that directory.

How one uses the files depends upon what display mechanism one chooses. I am working on a JavaScript image rotating system but anything that rotates through the PNG files and refreshes them every minute would be fine.

A future patch will establish an HTML_ONLY option so the display engine to the screen is not used. This makes it strictly for PNG file generation.

**Comment by n1kdo** [comment]
merged this.  thank you.
